name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup Visual Studio environment
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.0' # VS 2022

    - name: Configure project
      run: cmake -S . -B build -G "Visual Studio 17 2022" -DRAPI_DHT_USE_GPU=OFF

    - name: Build project
      run: cmake --build build --config Release

    - name: Run CPU smoke tests
      run: |
        cd build/Release
        test_smoke.exe --gtest_filter=*CPU*
